wsl-service: Print error if we can't find init.
This should make it easier to troubleshoot issues (instead of having a
generic "nsenter: invalid number ''").

Addresses:
https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/17#pullrequestreview-807775994

Signed-off-by: Mark Yen <mark.yen@suse.com>

diff --git a/files/wsl-service b/files/wsl-service
--- a/files/wsl-service
+++ b/files/wsl-service
@@ -14,4 +14,9 @@ set -o errexit -o nounset
 parent="$(cat /run/wsl-init.pid)"
 pid="$(ps -o pid,ppid,comm | awk '$2 == "'"${parent}"'" && $3 == "init" { print $1 }')"
 
+if [ -z "${pid}" ]; then
+    echo "Could not find init process" >&2
+    exit 1
+fi
+
 exec /usr/bin/nsenter -p -m -t "${pid}" /sbin/rc-service "$@"
